### PR TITLE
Fix for update 6

### PR DESCRIPTION
**Pull request by elMooXos**
Thx Hyphen-ated for his patience :)

The IGT doesn't work as the memory addresses seem to have changed

### CODE REVIEW

**Comment by elMooXos** [comment]
Values changed for the last update and gametime removed as suggested by stfx

**Comment by BatedUrGonnaDie** [comment]
Looks good to me, although can @stfx please clarify why gametime is being removed?

**Comment by elMooXos** [comment]
From his point of view, it's because the new game feature displays the time automatically at the end:
> Either way the livesplit gametime was only added to get the time if you forgot to open the menu in earlier versions(edited)
> Since the time now always is displayed on screen it is probably not needed anymore and support could be removed in the livesplit script as well

**Comment by BatedUrGonnaDie** [comment]
Ah, that makes sense.  Thanks for clarifying.

**Comment by elMooXos** [comment]
stfx reverted back the update, you can delete the last commit as 26th of january's works back

**Comment by elMooXos** [comment]
@BatedUrGonnaDie I don't know if you can read the previous message, so I ping you, stfx reverted to update 5 so my changes are not needed (the version from 26th of january works)
Thx

**Comment by TheMooXcom** [comment]
@BatedUrGonnaDie I don't know if you can read the previous message, so I ping you, stfx reverted to update 5 so my changes are not needed (the version from 26th of january works)
Thx

**Comment by stfx** [comment]
@BatedUrGonnaDie While we are at it could I get write rights to this repo since I am usually around when an update happens?

**Comment by BatedUrGonnaDie** [comment]
Is there something wrong with doing pull requests @stfx ?

**Comment by stfx** [comment]
Absolutely not, I would just like to accept PRs as fast as possible after an update

**Pull request merged**
