### PR TITLE
WIP: Maybe new pointers for Refunct Update 9

### PR DESCRIPTION
**Pull request by oberien**
Works for 3/5 people so far.

### CODE REVIEW

**Comment by stfx** [comment]
Awesome, hopefully you can eventually find those that work for 10/10 people;)

**Comment by BatedUrGonnaDie** [comment]
Works for me as well.

**Comment by oberien** [comment]
After force-pushing the commit so far the pointers worked for everyone, which I'm very pleased with!

**Comment by stfx** [comment]
It works on my system too so it seems like you found the correct ones, good job!

**Pull request merged**
